### ISSUE TITLE
Can you write some instructions on how to develop using your template?

### ISSUE THREAD

**Issue by jymchng** [BrianPugh/python-template#152]
For example, we can start with the list of tools that are available once we have set up using `./bootstrap`, and documenting simple kickstarter instructions like `ruff check .` to use `ruff` to lint all Python codes found within the current directory and so on.

More importantly, I realize I don't really know how to preview the documentation, all you mentioned in the `README.rst` is that we should import the repository onto `ReadTheDocs`, I mean - sure - but that would be too late.

**Comment by BrianPugh** [comment]
Hi @jymchng!

The README states that this template uses [pre-commit](https://pre-commit.com), and the bootstrap script automatically runs `pre-commit install`, meaning that it will automatically run whenever `git commit` is ran. This will run all the tools, including `ruff`. If you have specific suggestions about something I can add to the README, I'd be more than happy to! I could add a small sentence in the pre-commit bulletpoint explaining this. Maybe something like:

> * [Pre-commit](https://pre-commit.com/) linting and static analysis. The following hooks are pre-configured and will automatically run on `git commit`:

I can add a small section about building/previewing docs. **I'm trying to not have the README be a general tutorial for all the tools used**, but this seems pretty helpful and is pretty terse:
```
cd docs/
make html
# this results in html files in docs/build/html/
# Double click docs/build/html/index.html to view the docs in your web browser.
# This is exactly the same as would be shown on readthedocs.io
```

**Comment by jymchng** [comment]
I think the text is extremely helpful as well and I noted on the pre-commit hooks which is also helpful.
