### ISSUE TITLE
Unable to pip install from the local folder after `poetry build --format sdist`.

### ISSUE THREAD

**Issue by jymchng** [BrianPugh/python-template#157]
More details can be found in this issue: https://github.com/mtkennerly/poetry-dynamic-versioning/issues/126 on the last comment made by myself.

Thank you.

**Comment by BrianPugh** [comment]
Let's keep the discussion over here since this is unrelated to https://github.com/mtkennerly/poetry-dynamic-versioning/issues/126.

Did you follow the template instructions? It appears your project is not using git or doesn't have a `.git` folder.

**Comment by BrianPugh** [comment]
if you can share your repo, I can investigate.

**Comment by jymchng** [comment]
Thank you for your kind offer.

https://github.com/jymchng/simple-python-template

This is the repository. I had expanded on the `build.py` file, my goal is to be able to distribute the C extension modules to any user.

**Comment by jymchng** [comment]
Hi Brian

I apologize for not informing you earlier that I don't use your bootstrap script, hence it should work without going through the bootstrap step.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BrianPugh** [comment]
After disabling the `testpypi` poetry source, it builds and installs fine for me.

**Comment by jymchng** [comment]
> After disabling the `testpypi` poetry source, it builds and installs fine for me.

That's nice! Would you mind sharing what were the commands you ran?

Mine were:

```
poetry build --format sdist
# ./dist/simple_python_template-0.0.0.tar.gz is created
python -m pip install dist/simple_python_template-0.0.0.tar.gz
```

**Comment by BrianPugh** [comment]
same commands work on my machine.

**Comment by jymchng** [comment]
I am still facing the same problem sadly!

**Comment by BrianPugh** [comment]
when building the resulting tar should look like:
```console
$ ls -alh dist/
total 224
drwxr-xr-x@  3 brianpugh  staff    96B Aug  2 09:48 .
drwxr-xr-x@ 26 brianpugh  staff   832B Aug  2 09:37 ..
-rw-r--r--@  1 brianpugh  staff   111K Aug  2 09:48 simple_python_template-0.0.0.post13+b2aab4a.tar.gz
```

**Comment by BrianPugh** [comment]
closing due to unable to reproduce.
