### ISSUE TITLE
Issue with pyright when running ./bootsrap

### ISSUE THREAD

**Issue by ArianeDucellier** [BrianPugh/python-template#25]
Hi, I tried to use the template today, but ran into an issue with pyright. When running ./bootstrap, I get the error message:

pyright..................................................................Failed
- hook id: pyright
- exit code: 250

WARNING: there is a new pyright version available (v1.1.309 -> v1.1.310).
Please install the new version or set PYRIGHT_PYTHON_FORCE_VERSION to `latest`

Assertion failed: ((static_cast<size_t>(off - 1)) <= (sizeof(arrow) - 1)), function AppendExceptionLine, file ../src/node.cc, line 1404.

Traceback (most recent call last):
  File "./bootstrap", line 244, in <module>
  File "./bootstrap", line 235, in main
  File "./bootstrap", line 54, in git
  File "/opt/anaconda3/envs/wmtsa/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/anaconda3/envs/wmtsa/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'commit', '-m', 'bootstrap from template']' returned non-zero exit status 1.

Do you have any idea what that is?

Thank you very much.

**Comment by BrianPugh** [comment]
try running `pre-commit autoupdate` before running `bootstrap`. Basically the Pyright (python static analyzed, similar to mypy) pre-commit plugin notices that there's a newer version and says to update to it.

I also just ran `pre-commit autoupdate` in the repo, so if you clone again, you should be good.

**Comment by BrianPugh** [comment]
I also just added `pre-commit autoupdate` to now be part of bootstrap, and to not run `pre-commit` on the first boostrapping commit, so this issue shouldn't come up again.

**Comment by ArianeDucellier** [comment]
Thank you, it works now.
