### ISSUE TITLE
cythonize py files?

### ISSUE THREAD

**Issue by jheintz** [BrianPugh/python-template#37]
This project looks awesome! And I couldn't find anything like it, thanks!!

i'm trying to cythonize python files and compile them to c (for performance and not open source reasons).

I think that the build.py file is hard coded to look for .c and maybe .pyx files, and doesn't not look for *.py files.

this code, inside a setup.py, has done what I wanted before. but it's in a setup.py and can't use cibuildwheel.

    ext_modules=cythonize(
        "<top-level-dir>/**/*.py",
        compiler_directives={'language_level': 3, "linetrace": False},

I tried to figure out what to do for a setuptools Extension to do the same thing and didn't quite get things to work.

Is there already a way to cython the *.py files that I missed? Or what would you recommend?

**Comment by BrianPugh** [comment]
I'm still learning cython myself, butI think you can just add the path to all the python files you want to cythonize to the list here:

https://github.com/BrianPugh/python-template/blob/9e217e7d27ee91c7da70ef7c55bd2445b47c685e/build.py#L42

You can also do it programmatically, like if all the python files you want are in the directory `foo/`, you could add `*Path("foo").rglob("*.py")`.

**Comment by jheintz** [comment]
Thanks! I think this worked, and I now see *.c files produced for *.py files. This is what I added:

`
    c_files = [str(x) for x in Path("librarytemplate/_c_src").rglob("*.c")]
    **py_files = [str(x) for x in Path("librarytemplate/").rglob("*.py")]**
    extensions = [
        Extension(
            # Your .pyx file will be available to cpython at this location.
            "librarytemplate._c_extension",
            [
                # ".c" and ".pyx" source file paths
                "librarytemplate/_c_extension.pyx",
                *c_files,
                *py_files,
            ],
`

**Comment by jheintz** [comment]
Thanks, I'll close this issue
