### ISSUE TITLE
Add check during bootstrap if poetry is working

### ISSUE THREAD

**Issue by mgorfer** [BrianPugh/python-template#46]
I had a bit of trouble setting up this template.

When I ran `bootstrap`, it would ask me to fill out all the details, and after that fail because of
`error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory`

The reason was, that poetry was already installed, but not working. Stopping the bootstrap early in that case would be a nicer user experience.
Just using `poetry --version` after `check_and_install_poetry()` would be my suggestion. Installing poetry did not create any errors on my side, but running `poetry --version` led to the error above.

After removal of the faulty poetry and the correct setup of my pyenv the bootstrap successfully finished.

_And thank you very much for creating this awesome template. I already learned a lot while trying to understand what is going on here._

**Comment by BrianPugh** [comment]
Addressed in #47. I understand how annoying it can be having to refill out the prompts.

Thanks for the kind words! Please let me know if you run into any other issues or have any suggestions. Thanks!
