### ISSUE TITLE
Consider using cookiecutter for the template

### ISSUE THREAD

**Issue by YisusChrist** [BrianPugh/python-template#86]
First of all, I love the way all the setup is designed, there  is clearly a lot of effort.

Nevertheless I think it could be a good idea to try to adapt the template design and convert it to a [cookiecutter](https://github.com/cookiecutter/cookiecutter) template. It is a widely used Python templates manager and the most nearly standardized way of creating new projects from templates and **creating custom templates** fully customizable. Also cross-platform support out of the box, which is great.

I think this template could be improved with that change and be used by more people.

>Note: If you need some references of preexisting Python project templates using cookiecutter the best ones IMO are these:
> - https://github.com/audreyfeldroy/cookiecutter-pypackage (Quite simple and efficient but is not up to date with [PEP 517](https://peps.python.org/pep-0517/))
> - https://github.com/cjolowicz/cookiecutter-hypermodern-python (Fully equipped template with lots of functionalities and CI/CD integration).

**Comment by BrianPugh** [comment]
I previously used cookiecutter, but explicitly chose not to for this project for the following reasons:

1. Greater customization/control over the project creation process.
2.`bootstrap` uses naive find/replace, where the find tokens are still valid identifiers in most (python, toml, etc) languages. This allows CI, static analyzers, autocomplete to still work on the template. This wouldn't be possible with a jinja2-based template. This makes maintenance and adding features much easier and less error-prone.
3. `bootstrap` uses only python builtins, lowering the bar to entry slightly.
